apiVersion: v1
kind: Service
metadata:
  name: kindle-clippings-nodeport-service
spec:
  type: NodePort
  selector:
    aLabel: kindle-clippings-depl
  ports:
    - name: kindle-clippings-nodeport-service
      protocol: TCP
      port: 8080
      targetPort: 8080 